# Generated by Django 4.2.9 on 2024-01-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
